"""lib/l10n/app_tr.arb dosyasını aşağıdaki tablodan üretir.

Yer tutucular {ad} biçiminde yazılır; tam sayı olanlar {ad#} ile
işaretlenir. Metin ekledikten sonra:
    python tool/arb_uret.py && flutter gen-l10n
"""
import json
import re

M = {}


def m(anahtar, metin):
    assert anahtar not in M, anahtar
    M[anahtar] = metin


# --- Genel -----------------------------------------------------------------
m("uygulamaAdi", "Abyad")
m("geri", "Geri")
m("tamam", "Tamam")
m("vazgec", "Vazgeç")
m("devam", "Devam")
m("atla", "Atla")
m("acik", "Açık")
m("kapali", "Kapalı")
m("bugun", "Bugün")
m("gecti", "Geçti")
m("tumu", "Tümü")
m("onceki", "Önceki")
m("sonucYok", "Sonuç bulunamadı")
m("veriOkunamadi", "İçerik yüklenemedi. Uygulamayı kapatıp yeniden açmayı deneyin.")
m("artir", "{ad}: artır")
m("azalt", "{ad}: azalt")
m("yuzdeDeger", "%{yuzde#}")
m("kaynakSatiri", "Kaynak: {kaynak}")
m("okunus", "Okunuşu")
m("anlam", "Anlamı")
m("namaz", "Namaz")
m("abdest", "Abdest")
m("oruc", "Oruç")

# --- Alt menü ve ekran başlıkları ------------------------------------------
m("menuEtiketi", "Ana menü")
m("menuAnaSayfa", "Ana Sayfa")
m("menuVakitler", "Vakitler")
m("menuKuran", "Kur'an")
m("menuDualar", "Dualar")
m("menuGunler", "Günler")
m("ekranVakitler", "Namaz Vakitleri")
m("ekranKuran", "Kur'an-ı Kerim")
m("ekranDualar", "Dualar ve Zikir")
m("ekranGunler", "Önemli Günler")

# --- Vakitler --------------------------------------------------------------
m("vakitImsak", "İmsak")
m("vakitGunes", "Güneş")
m("vakitOgle", "Öğle")
m("vakitIkindi", "İkindi")
m("vakitAksam", "Akşam")
m("vakitYatsi", "Yatsı")
m("siradakiVakit", "Sıradaki vakit · {vakit}")
m("siradakiVakitOkuma", "Sıradaki vakit {vakit}, saat {saat}, {kalan}")
m("kalanSaatDakika", "{saat#} saat {dakika#} dakika kaldı")
m("kalanDakika", "{dakika#} dakika kaldı")
m("vakitCipiOkuma", "{vakit} {saat}")
m("vakitCipiSiradakiOkuma", "{vakit} {saat}, sıradaki vakit")
m("vakitCipiSimdikiOkuma", "{vakit} {saat}, şu anki vakit")
m("siradakiVakitRozet", "Sıradaki vakit")
m("suAnkiVakitRozet", "Şu anki vakit")
m("tarihSatiri", "{hicri} · {miladi}")
m("hicriTarih", "{gun#} {ay} {yil#}")
m("hicriAylar", "Muharrem,Safer,Rebiülevvel,Rebiülâhir,Cemâziyelevvel,Cemâziyelâhir,Receb,Şâban,Ramazan,Şevval,Zilkade,Zilhicce")
m("vakteKalan", "{vakit} vaktine kalan")
m("vakteKalanOkuma", "{vakit} vaktine {kalan}")
m("oncekiGun", "Önceki gün")
m("sonrakiGun", "Sonraki gün")
m("buguneDon", "Bugüne dönmek için dokunun")
m("oncekiAy", "Önceki ay")
m("sonrakiAy", "Sonraki ay")
m("aylikImsakiye", "Aylık imsakiye")
m("kuranMetniBaslik", "Metin ve İşaretler")
m("kuranMetniDugme", "Kur'an metni ve işaretler hakkında")
m("kuranMetniBolum", "Bu metin hakkında")
m("kuranIsaretBolum", "Durak ve secde işaretleri")
m("icerikIncelenmedi", "Bu sayfadaki bilgiler henüz bir hoca tarafından incelenmedi.")
m("ekVakitlerKart", "Kerahat, işrak ve teheccüd vakitleri")
m("ekVakitlerBaslik", "Kerahat, İşrak ve Teheccüd")
m("ekNafileBolum", "Nafile namaz vakitleri")
m("ekKerahatBolum", "Kerahat vakitleri")
m("saatAraligi", "{bas} – {bit}")
m("saatAraligiOkuma", "{bas} ile {bit} arası")
m("ekVakitYok", "Bu tarihte hesaplanamıyor")
m("suAnKerahat", "Şu an kerahat vakti")
m("ekVakitlerYaklasik", "Bu saatler namaz vakitlerinden türetilen yaklaşık değerlerdir.")
m("ekVakitlerIncelenmedi", "Süreler ve açıklamalar henüz bir hoca tarafından incelenmedi.")
m("yuksekEnlemBaslik", "Bu vakitler neden farklı olabilir?")
m("yuksekEnlemMetin", "Bulunduğunuz enlemde bu tarihte {vakitler} vakti astronomik olarak oluşmuyor; yüksek enlemlerde yaz gecelerinde gökyüzü tam kararmaz. Abyad bu günlerde \"gecenin yedide biri\" kuralını uygular: geceyi yediye böler, yatsıyı akşamdan bir pay sonra, imsakı güneş doğmadan bir pay önce alır. Diyanet bu enlemler için başka bir usul uyguladığından onun takvimiyle fark yarım saati aşabilir; oruç ve namaz için caminizin takvimini esas alın. Ayarlar'dan her vakte dakika düzeltmesi ekleyebilirsiniz.")
m("yazFarkiMetin", "Diyanet, bu enlemde yaz aylarında imsak ve yatsıyı kısaltılmış bir süreyle yayımlıyor. Abyad ise güneşin açısına göre hesaplar; bu yüzden burada imsak Diyanet takviminden daha erken, yatsı daha geç görünebilir ve fark bir saati aşabilir. Caminizin takvimini esas alın; Ayarlar'dan her vakte dakika düzeltmesi ekleyebilirsiniz.")
m("listeVe", "{ilk} ve {son}")
m("ezanBildirimiAcik", "{vakit} ezan bildirimi açık")
m("ezanBildirimiKapali", "{vakit} ezan bildirimi kapalı")
m("hesaplamaYontemiNotu", "Hesaplama yöntemi: {yontem} · Ayarlardan değiştirilebilir")
m("yontemDiyanet", "Diyanet İşleri Başkanlığı")
m("yontemDunyaIslamBirligi", "Dünya İslam Birliği")
m("yontemKuzeyAmerika", "Kuzey Amerika (ISNA)")
m("yontemMisir", "Mısır")
m("bildirimler", "Bildirimler")

# --- Kıble -----------------------------------------------------------------
m("kibleBaslik", "Kıble")
m("kibleYonu", "Kıble yönü")
m("kibleDerece", "{derece#}° {yon}")
m("kibleKartOkuma", "Kıble yönü {derece#} derece {yon}. Pusulayı açmak için dokunun")
m("pusulayiAc", "Pusulayı aç")
m("kibleHizada", "Kıbleye döndünüz")
m("kibleSagaDon", "{derece#}° sağa dönün")
m("kibleSolaDon", "{derece#}° sola dönün")
m("kibleTitresim", "Kıbleye dönünce titreşim")
m("kibleTitresimAciklama", "Telefon kıbleye hizalanınca hafifçe titrer.")
m("pusulaIpucu", "Telefonu yere paralel tutun. Yön şaşıyorsa telefonu havada 8 çizer gibi hareket ettirerek kalibre edin.")
m("pusulaYokBaslik", "Pusula sensörü bulunamadı")
m("pusulaYokMetin", "Bu telefonda pusula kullanılamıyor. Kıble yönünüz kuzeyden saat yönünde {derece#}° ({yon}).")
m("kalibrasyonBaslik", "Pusula kalibrasyonu gerekiyor")
m("kalibrasyonMetin", "Telefonu havada 8 çizer gibi birkaç kez hareket ettirin. Mıknatıs, hoparlör ve metal eşyalardan uzak tutun.")
m("kuzeyKisaltma", "K")
m("yonKuzey", "Kuzey")
m("yonKuzeydogu", "Kuzeydoğu")
m("yonDogu", "Doğu")
m("yonGuneydogu", "Güneydoğu")
m("yonGuney", "Güney")
m("yonGuneybati", "Güneybatı")
m("yonBati", "Batı")
m("yonKuzeybati", "Kuzeybatı")

# --- Konum -----------------------------------------------------------------
m("konum", "Konum")
m("konumSec", "Konum Seç")
m("konumDegistirOkuma", "Konum: {sehir}. Değiştirmek için dokunun")
m("konumOtomatik", "Otomatik · {sehir}")
m("sehirAraIpucu", "İl, ilçe veya şehir ara")
m("sehirBulunamadi", "Aradığınız yer bulunamadı. Yakındaki bir ilçeyi ya da ili deneyin.")
m("konumumuKullan", "Konumumu kullan")
m("konumAraniyor", "Konum aranıyor…")
m("konumMahremiyet", "Konumunuz yalnızca vakitleri hesaplamak için kullanılır ve telefonunuzda kalır.")
m("konumServisKapali", "Telefonun konum servisi kapalı.")
m("konumIzinYok", "Konum izni verilmedi. Şehrinizi listeden seçebilirsiniz.")
m("konumIzinKalici", "Konum izni kapalı. Telefonun ayarlarından açabilir ya da şehrinizi listeden seçebilirsiniz.")
m("konumBulunamadi", "Konum bulunamadı. Şehrinizi listeden seçebilirsiniz.")

# --- Ana Sayfa -------------------------------------------------------------
m("hizliKible", "Kıble")
m("hizliKuran", "Kur'an")
m("hizliZikirmatik", "Zikirmatik")
m("hizliDualar", "Dualar")
m("devamEt", "Kaldığın yerden devam et")
m("devamKonum", "{sure} · {ayet#}. ayet")
m("hatimDurumu", "Hatim %{yuzde#} · Sayfa {sayfa#} / {toplam#}")
m("devamOkuma", "Kaldığın yerden devam et: {sure}, {ayet#}. ayet. Hatim yüzde {yuzde#}")
m("kuranaBasla", "Kur'an okumaya başla")
m("kuranaBaslaAlt", "Kaldığınız yer burada görünecek")
m("gununAyeti", "Günün Ayeti")
m("ayetKaynagi", "{sure} Suresi, {ayet#}")
m("yaklasanGun", "Yaklaşan mübarek gün")
m("gunBirimi", "gün")
m("yaklasanGunOkuma", "Yaklaşan mübarek gün: {ad}, {tarih}, {kalan#} gün kaldı")
m("dahaFazlasi", "Daha fazlası")
m("rehberBaslik", "Namaz ve Abdest Rehberi")
m("rehberAciklama", "Yeni başlayanlar için adım adım")
m("kazaAciklama", "Kaza namazı ve oruç sayaçları")

# --- Kur'an ----------------------------------------------------------------
m("kuranAraIpucu", "Sure adı veya sure:ayet ara")
m("sekmeSure", "Sure")
m("sekmeCuz", "Cüz")
m("sekmeSayfa", "Sayfa")
m("sekmeImlerim", "İmlerim")
m("kaldiginYer", "Kaldığın yer")
m("mekki", "Mekkî")
m("medeni", "Medenî")
m("sureBilgisi", "{tur} · {ayet#} ayet")
m("sureAdi", "{sure} Suresi")
m("sureAyet", "{sure} · {ayet#}. ayet")
m("sureAyetUzun", "{sure} Suresi · {ayet#}. ayet")
m("sureUstBilgi", "{no#}. sure · {ayet#} ayet · {tur} · Sayfa {sayfa#}")
m("cuzNo", "{no#}. Cüz")
m("sayfaNo", "Sayfa {no#}")
m("sayfaCuz", "Sayfa {sayfa#} · {cuz#}. cüz")
m("hatimYuzde", "Hatim %{yuzde#}")
m("yerImiYok", "Henüz yer imi yok. Okurken bir ayetin yanındaki işarete dokunarak ekleyebilirsiniz.")
m("yerImiEkle", "{ayet#}. ayete yer imi ekle")
m("yerImiKaldir", "{ayet#}. ayetin yer imini kaldır")
m("ayetNo", "{no#}. ayet")
m("modArapcaMeal", "Arapça + Meal")
m("modArapca", "Arapça")
m("modMeal", "Meal")
m("mealYok", "Meal kaynağı eklenecek. Türkçe meal, lisans izni alındıktan sonra burada görünecek.")
m("mealYokKisa", "Meal kaynağı eklenecek")
m("sonrakiSure", "Sonraki sure: {sure}")
m("tanzilKaynak", "Arapça metin: Tanzil Projesi (tanzil.net)")
m("yaziBoyutuVeGorunum", "Yazı boyutu ve görünüm")
m("sayfaGorunumu", "Sayfa görünümü")
m("ayetGorunumu", "Ayet ayet görünüm")
m("sayfaSayisi", "Sayfa {sayfa#} / {toplam#}")
m("oncekiSayfa", "Önceki sayfa")
m("sonrakiSayfa", "Sonraki sayfa")
m("sayfayaGit", "Sayfaya git")
m("sayfaNoIpucu", "1–604")
m("yerImiEkleKisa", "Yer imi ekle")
m("yerImiKaldirKisa", "Yer imini kaldır")
m("mealSecimi", "Meal")
m("mealEklenmedi", "Eklenmedi")
m("kuranGorunumu", "Kur'an görünümü")
m("lisansMealKaydi", "{ad} — {sahip}. {lisans}")
m("arapcaYaziBoyutu", "Arapça yazı boyutu")
m("arapcaYaziBoyutuNot", "Yalnızca Kur'an okuma ekranlarındaki Arapça metni etkiler. Genel yazı boyutu Ayarlar'dan değiştirilir.")

# --- Dualar ve Zikirmatik --------------------------------------------------
m("kategoriler", "Kategoriler")
m("zikirmatik", "Zikirmatik")
m("namazSonrasiTesbihat", "Namaz sonrası tesbihat")
m("tesbihatOzet", "Sübhânallah · Elhamdülillah · Allâhu Ekber")
m("sayaciSifirla", "Sayacı sıfırla")
m("dokunVeSay", "Dokun ve say")
m("zikirSayOkuma", "{zikir} say, şu an {sayi#}")
m("turTamamlandi", "{tur#} tur tamamlandı · Allah kabul etsin")
m("hedef", "Hedef")
m("hedefSerbest", "Serbest")
m("bugunkuToplam", "Bugünkü toplam zikir")
m("bugunkuToplamOkuma", "Bugünkü toplam zikir: {adet#}")
m("zikirTitresim", "Dokununca titreşim")
m("zikirTumEkran", "Ekranın her yerine dokunarak say")
m("zikirTumEkranAciklama", "Telefona bakmadan sayabilirsiniz.")
m("zikirEkranAcik", "Ekran kapanmasın")
m("zikirArkaPlan", "Arka planda manzara")
m("zikirArkaPlanAciklama", "Kâbe, Medine, Kudüs ve tarihî camilerin görselleri sayacın arkasında sırayla görünür.")
m("zikirArkaPlanSure", "Değişme aralığı")
m("saniyeKisa", "{saniye#} sn")
m("dakikaKisa", "{dakika#} dk")
m("manzaraKabe", "Kâbe")
m("manzaraMekke", "Mekke")
m("manzaraMedine", "Medine")
m("manzaraKudus", "Kudüs")
m("manzaraSelimiye", "Selimiye Camii")
m("manzaraAyasofya", "Ayasofya")
m("manzaraUlucami", "Ulu Cami")
m("ozelZikir", "Özel zikir")
m("ozelZikirEkle", "+ Özel zikir")
m("ozelZikirIpucu", "Zikri yazın")

# --- Önemli Günler ---------------------------------------------------------
m("gunlerDonem", "Hicrî {yil#} · {donem}")
m("siradakiMubarekGun", "Sıradaki mübarek gün")
m("gunKaldi", "gün kaldı")
m("kalanGun", "{gun#} gün")
m("hatirlat", "Hatırlat")
m("hatirlatmaAcik", "Hatırlatma açık")
m("gunHatirlatmaAcik", "{gun} hatırlatması açık")
m("gunHatirlatmaKapali", "{gun} hatırlatması kapalı")
m("tarihAraligi", "{ilk#}–{son#} {ayYil}")
m("gunlerNot", "Tarihler resmî dinî günler takvimine göre güncellenir.")

# --- Ayarlar ---------------------------------------------------------------
m("ayarlar", "Ayarlar")
m("okunabilirlik", "Okunabilirlik")
m("yaziBoyutu", "Yazı boyutu")
m("yaziNormal", "Normal")
m("yaziBuyuk", "Büyük")
m("yaziCokBuyuk", "Çok büyük")
m("yaziOrnegi", "Bu metin, seçtiğiniz yazı boyutunun örneğidir.")
m("yaziBoyutuNot", "Seçtiğiniz boyut bütün ekranlarda, Kur'an ve dualar dahil uygulanır. Telefonun kendi yazı boyutu ayarına da uyar.")
m("yuksekKontrast", "Yüksek kontrast")
m("yuksekKontrastAciklama", "Yazı ve zemin arasındaki farkı artırır.")
m("ezanVeBildirimler", "Ezan ve bildirimler")
m("ezanVeBildirimlerOzet", "Vakit sesleri, hatırlatma ve test bildirimi")
m("konumVeVakitler", "Konum ve vakitler")
m("kuranAyarOzet", "Okuma görünümü ve meal")
m("tema", "Tema")
m("temaAcik", "Açık")
m("temaKoyu", "Koyu")
m("alarmOlarakCal", "Ezanı alarm olarak çal")
m("alarmOlarakCalAciklama", "Medya sesi kısık olsa da, ekran kapalıyken de ezan duyulur.")
m("onceHatirlat", "Vakitten 15 dk önce hatırlat")
m("onceHatirlatAciklama", "Özellikle sabah ve sahur için ikinci bir uyarı.")
m("cumaSessiz", "Cuma namazında sessiz")
m("cumaSessizAciklama", "Cuma günü öğle vaktinde ezan yerine titreşim.")
m("vakitBildirimleri", "Vakit bildirimleri")
m("vakitBildirimleriAciklama", "Her vakit için aç/kapa ve ses seçimi")
m("sesEzan", "Ezan")
m("sesKisa", "Kısa uyarı")
m("sesTitresim", "Titreşim")
m("ezanSesiYokNot", "Ezan kaydı henüz eklenmedi; \"Ezan\" seçili vakitlerde telefonun varsayılan bildirim sesi çalar.")
m("bildirimIzniYok", "Bildirim izni verilmedi; ezan vakitlerinde bildirim gelmez.")
m("bildirimIzniVer", "Bildirimlere izin ver")
m("tamZamanliYok", "Tam zamanlı alarm izni kapalı; ezan birkaç dakika gecikebilir.")
m("tamZamanliIzinVer", "Tam zamanlı alarma izin ver")
m("testBildirimiAciklama", "Ezan bildiriminin telefonunuzda çaldığını hemen doğrulayın.")
m("testBildirimiGonder", "Test bildirimi gönder")
m("testBildirimiGonderildi", "Birkaç saniye içinde bildirim gelecek.")
m("pilBaslik", "Ezanın her durumda çalması için")
m("pilMetin", "Telefonunuz pil tasarrufu için uygulamayı durdurabilir. Bu uygulama için pil optimizasyonunu kapatın.")
m("ayariAc", "Ayarı aç")
m("markaSamsung", "Samsung")
m("markaSamsungYol", "Ayarlar > Uygulamalar > Abyad > Pil > \"Kısıtlamasız\" seçin.")
m("markaXiaomi", "Xiaomi")
m("markaXiaomiYol", "Ayarlar > Uygulamalar > Abyad > Pil tasarrufu > \"Kısıtlama yok\" seçin; ayrıca \"Otomatik başlatma\"yı açın.")
m("markaHuawei", "Huawei / Honor")
m("markaHuaweiYol", "Ayarlar > Uygulamalar > Uygulama başlatma > Abyad > \"Elle yönet\" seçip üç seçeneği de açın.")
m("vakitHesaplama", "Vakit hesaplama")
m("hesaplamaYontemi", "Hesaplama yöntemi")
m("dakikaDuzeltme", "Vakitlere dakika ekle/çıkar")
m("dakikaDuzeltmeAciklama", "Camideki ezan vaktiyle fark varsa her vakit için dakika ekleyip çıkarabilirsiniz.")
m("dakikaArtir", "{vakit}: bir dakika ekle")
m("dakikaAzalt", "{vakit}: bir dakika çıkar")
m("dakikaDeger", "{dakika#} dakika")
m("hicriDuzeltme", "Hicrî tarih düzeltmesi")
m("hicriDuzeltmeAciklama", "Hicrî gün, bulunduğunuz yerdeki takvimden bir gün farklıysa düzeltin.")
m("gunEksiBir", "−1 gün")
m("gunFarkiYok", "Düzeltme yok")
m("gunArtiBir", "+1 gün")
m("mahremiyetBaslik", "Mahremiyetiniz emanettir")
m("mahremiyetMetin", "Bu uygulama hiçbir veri toplamaz, reklam göstermez ve hesap istemez. Konumunuz sadece vakitleri hesaplamak için bu telefonda kullanılır, hiçbir yere gönderilmez.")
m("kaynaklarVeLisanslar", "Kaynaklar ve Lisanslar")
m("surumBilgisi", "Sürüm {surum} · Ücretsizdir, ücretsiz kalacaktır.")
m("lisansKuranBaslik", "Kur'an-ı Kerim metni")
m("lisansKuranMetin", "Arapça metin, Tanzil Projesi'nin Uthmani metnidir (sürüm 1.1, tanzil.net). Creative Commons Attribution 3.0 lisansı gereği metin değiştirilmeden kullanılmıştır. Sure, cüz ve sayfa bilgileri de Tanzil üst verisinden gelir.")
m("lisansMealBaslik", "Türkçe meal")
m("lisansMealMetin", "Henüz bir meal eklenmedi. Meal, yalnızca hak sahibinden izin alındıktan sonra eklenecektir.")
m("lisansSehirBaslik", "Şehir koordinatları")
m("lisansSehirMetin", "İl, ilçe ve yurt dışı şehir koordinatları GeoNames (geonames.org) verisinden alınmıştır. Creative Commons Attribution 4.0.")
m("lisansYaziBaslik", "Yazı tipleri")
m("lisansYaziMetin", "Manrope, Fraunces ve Amiri; SIL Open Font License 1.1 ile lisanslıdır.")
m("lisansEzanBaslik", "Ezan sesi")
m("lisansEzanMetin", "Henüz ezan kaydı eklenmedi; telefonun varsayılan bildirim sesi kullanılıyor. Kayıt, yalnızca izinli ya da lisanslı bir kaynaktan eklenecektir.")
m("lisansIcerikBaslik", "Dua ve bilgi metinleri")
m("lisansIcerikMetin", "Dualar, okunuşlar, Esmâ-ül Hüsnâ anlamları ve rehber metinleri yayın öncesinde bir hoca tarafından incelenecektir. Vakit hesaplama parametreleri açık kaynaklı Adhan kütüphanesindeki Türkiye yöntemine dayanır.")
m("lisansHadisBaslik", "Kırk Hadis")
m("lisansHadisMetin", "Hadislerin Arapça metni İmam Nevevî'nin Kırk Hadis'inden (el-Erbaûn) alınmıştır; eser kamu malıdır. Türkçe tercümeler Abyad için hazırlanmıştır ve yayın öncesinde bir hoca tarafından incelenecektir.")
m("lisansCizimBaslik", "Çizimler ve görseller")
m("lisansCizimMetin", "Namaz ve abdest rehberindeki çizimler Abyad için hazırlanmıştır; başka bir kaynaktan alınmamıştır. Zikirmatik arka planındaki manzara görselleri yapay zekâ ile üretilmiştir; fotoğraf değildir, mekânları temsilen gösterir.")
m("lisansPaketler", "Kullanılan yazılım paketleri")

# --- Bildirim metinleri ----------------------------------------------------
m("kanalEzanAlarm", "Ezan (alarm sesiyle)")
m("kanalEzan", "Ezan")
m("kanalHatirlatma", "Hatırlatmalar")
m("kanalTitresim", "Sessiz (titreşim)")
m("kanalAciklama", "Namaz vakti bildirimleri")
m("bildirimVakitBaslik", "{vakit} vakti")
m("bildirimVakitGovde", "{sehir} · {saat}")
m("bildirimOnceBaslik", "{vakit} vaktine {dakika#} dakika kaldı")
m("bildirimGunGovde", "Bugün mübarek bir gün. Hayırlara vesile olsun.")
m("bildirimTestBaslik", "Test bildirimi")
m("bildirimTestGovde", "Bu bildirimi duyduysanız ezan bildirimleri çalışıyor.")

# --- İlk açılış ------------------------------------------------------------
m("ilkAdim", "Adım {adim#} / {toplam#}")
m("ilkVaatBaslik", "Reklam yok, veri yok, hesap yok.")
m("ilkVaatMetin", "Abyad tamamen ücretsizdir ve öyle kalacak. Hiçbir verinizi toplamaz, internete bağlanmaz, sizden hesap istemez. Vakitler, Kur'an ve dualar telefonunuzun içindedir.")
m("ilkKonumBaslik", "Vakitler için konumunuz")
m("ilkKonumMetin", "Namaz vakitlerini bulunduğunuz yere göre hesaplamak için konumunuzu kullanırız. Konumunuz yalnızca vakitleri hesaplamak içindir, telefonunuzda kalır ve hiçbir yere gönderilmez. İsterseniz konum izni vermeden şehrinizi listeden seçebilirsiniz.")
m("ilkKonumAlinamadi", "Konum alınamadı. Şehrinizi listeden seçebilirsiniz.")
m("sehrimiSecerim", "Şehrimi listeden seçeyim")
m("simdilikAtla", "Şimdilik atla (İstanbul ile devam et)")
m("ilkBildirimBaslik", "Ezan vaktinde haber verelim")
m("ilkBildirimMetin", "Vakit girdiğinde ezan bildirimi gönderebilmemiz için bildirim iznine ihtiyacımız var. Hangi vakitlerde bildirim alacağınızı sonra Ayarlar'dan değiştirebilirsiniz.")
m("ilkBildirimMetinAndroid", "Vakit girdiğinde ezan bildirimi gönderebilmemiz için bildirim iznine ihtiyacımız var. Ezanın tam vaktinde çalması için telefonunuz \"Alarmlar ve hatırlatıcılar\" iznini de sorabilir. Bazı telefonlar pil tasarrufu için uygulamayı durdurur; bunu Ayarlar'daki yönergelerle kapatabilirsiniz.")

# --- Kaza Takibi -----------------------------------------------------------
m("kazaTakibi", "Kaza Takibi")
m("gizle", "Gizle")
m("goster", "Göster")
m("sayilariGizle", "Sayıları gizle")
m("sayilariGoster", "Sayıları göster")
m("kalanKaza", "Kalan kaza namazı")
m("tahminiBitis", "Tahmini bitiş")
m("kazaYok", "Borç yok")
m("kazaOzetGizli", "Kaza sayıları gizli")
m("kazaOzetOkuma", "Kalan kaza namazı {adet#}. Tahmini bitiş: {sure}")
m("gundeKacVakit", "Günde kaç vakit kaza kılarım?")
m("gundeVakit", "Günde {adet#} vakit")
m("bugunKazaKildiniz", "Bugün {adet#} kaza kıldınız. Allah kabul etsin.")
m("kazaSabah", "Sabah")
m("kazaVitir", "Vitir")
m("kazaOruc", "Ramazan kazası")
m("kazaKaldi", "{adet#} kaldı")
m("orucKaldi", "{adet#} gün kaldı")
m("kazaEkle", "{namaz} kazası ekle")
m("kazaKildimOkuma", "Bir {namaz} kazası kıldım")
m("kildim", "Kıldım")
m("tuttum", "Tuttum")
m("orucEkle", "Kaza orucu ekle")
m("orucTuttumOkuma", "Bir kaza orucu tuttum")
m("kazaNasilHesaplarim", "Kaza borcumu nasıl hesaplarım?")
m("kazaHesapAlt", "Adım adım hesaplama ve kısa fıkıh bilgisi")
m("kazaMahremiyet", "Bu bilgiler sadece bu telefonda saklanır.")
m("sureYilAy", "yaklaşık {yil#} yıl {ay#} ay")
m("sureYil", "yaklaşık {yil#} yıl")
m("sureAyGun", "yaklaşık {ay#} ay {gun#} gün")
m("sureAy", "yaklaşık {ay#} ay")
m("sureGun", "{gun#} gün")
m("kazaHesaplama", "Kaza Borcu Hesaplama")
m("kazaHesaplamaGiris", "Kaç yıl namaz kılmadığınızı ve oruç tutmadığınızı girin; yaklaşık kaza sayınızı hesaplayalım. Sonuç bir tahmindir, sayaçları sonradan elle düzeltebilirsiniz.")
m("sihirbazNamazYil", "Namaz kılmadığım yıl")
m("sihirbazNamazYilAciklama", "Buluğ çağından sonra namaz kılmadığınız süre.")
m("sihirbazNamazAy", "Ek ay")
m("sihirbazOzurGun", "Aylık özür günü (kadınlar)")
m("sihirbazOzurGunAciklama", "Âdet günlerinde kılınmayan namazların kazası yoktur; bu günler hesaptan düşülür.")
m("sihirbazOrucYil", "Oruç tutmadığım Ramazan sayısı")
m("sihirbazOrucYilAciklama", "Her Ramazan 30 gün sayılır.")
m("sihirbazSonuc", "Tahmini kaza borcu")
m("sihirbazSonucNamaz", "Her vakit ve vitir için {adet#} namaz")
m("sihirbazSonucOruc", "{adet#} gün oruç")
m("sihirbazUygula", "Sayaçlara uygula")
m("sihirbazOnayBaslik", "Sayaçlar değiştirilsin mi?")
m("sihirbazOnayMetin", "Mevcut kaza sayılarınız bu hesaplamanın sonucuyla değiştirilecek.")
m("kisaFikihBilgisi", "Kısa fıkıh bilgisi")
m("fikihNot", "Bu bilgiler Hanefi mezhebine göre özettir. Özel durumunuz için bir din görevlisine danışın.")

# --- Rehber ----------------------------------------------------------------
m("adimNo", "Adım {adim#} / {toplam#}")
m("cizimAlani", "Çizim alanı · {adim}")
m("sonrakiAdim", "Sonraki adım")
m("hareketiTekrarla", "Hareketi tekrar göster")
m("bastanBasla", "Baştan başla")

m("rehberNamazSec", "Öğrenmek istediğiniz namazı ve bölümünü seçin.")
m("rehberIcerikBekleniyor", "Bu bölümün içeriği hazırlanıyor.")
m("rekatSayisi", "{rekat#} rekat")
m("rehberBolumBasligi", "{vakit} – {bolum}")
m("rekatAdim", "{rekat#}. rekat · {adim}")
m("tekrarSayisi", "{adet#} kez")
m("ornekSure", "Örnek sure: {sure}")
m("kadinlarIcin", "Kadınlar için")
m("okunusuDinle", "Okunuşu dinle")
m("ezberAc", "Ezber modunu aç")
m("ezberKapat", "Ezber modunu kapat")
m("ezberAcik", "Ezber modu açık: Arapça metin ve okunuş gizli, görmek için dokunun.")
m("ezberGoster", "Göstermek için dokunun")
m("abdestRehberi", "Abdest Rehberi")
m("abdestAltBaslik", "Abdestin adım adım alınışı")
m("abdestRehberiAciklama", "Abdestin alınışı {adet#} adımda, çizimlerle anlatılır.")
m("abdestBasla", "Abdest adımlarına başla")
m("abdestiBozanlar", "Abdesti bozan durumlar")

# --- Hadis -----------------------------------------------------------------
m("hadisBaslik", "Kırk Hadis")
m("hadisAltBaslik", "Hz. Peygamber'in (s.a.v.) sözlerinden")
m("hadisAciklama", "İmam Nevevî'nin derlemesi")
m("hadisBekleniyorBaslik", "İçerik hazırlanıyor")
m("hadisBekleniyorMetin", "Hadisleri kaynağı ve tercümesi belli olmadan eklemiyoruz. Derleme seçilip bir hoca tarafından incelendikten sonra kırk hadis burada yer alacak.")
m("hadisNo", "{no#}. hadis")
m("hadisRavi", "Rivayet eden: {ravi}")
m("hadisTercume", "Tercüme: {kaynak}")
m("hadisHikayeEtiket", "Temsilî hikâye")
m("hadisHikayeNot", "Bu hikâye, hadisin daha iyi anlaşılması için yazılmış kurgusal bir anlatıdır; yaşanmış bir olay ya da rivayet değildir.")

# --- Toplu Hatim -----------------------------------------------------------
m("hatimBaslik", "Toplu Hatim")
m("hatimAciklama", "Hatmi cüz cüz, sayfa sayfa takip edin")
m("hatimYeni", "Yeni hatim")
m("hatimBaslat", "Hatim başlat")
m("hatimBosBaslik", "Henüz hatim yok")
m("hatimBosMetin", "Bir hatim başlatın; cüzleri ya da sayfaları pay pay alın, okudukça işaretleyin.")
m("hatimYerelNotBaslik", "Linkle paylaşım henüz açık değil")
m("hatimYerelNot", "Hatmi aileniz ve arkadaşlarınızla linkle paylaşma özelliği hazırlanıyor. Şimdilik hatmi bu telefonda başlatıp payları kendiniz takip edebilirsiniz. Bilgileriniz telefonunuzda kalır, hiçbir yere gönderilmez.")
m("hatimDevamEden", "Devam eden hatim")
m("hatimTamamlandi", "Hatim tamamlandı")
m("hatimIlerlemeCuz", "{okunan#} / {toplam#} cüz okundu")
m("hatimIlerlemePay", "{okunan#} / {toplam#} pay okundu")
m("hatimHedef", "Hedef: {tarih}")
m("hatimAdi", "Hatmin adı")
m("hatimAdiIpucu", "Örnek: Ramazan Aile Hatmi")
m("hatimNotu", "Niyet notu (isteğe bağlı)")
m("hatimNotuIpucu", "Örnek: Annemizin ruhu için")
m("hatimBolme", "Bölme şekli")
m("hatimCuzCuz", "Cüz cüz")
m("hatimSayfaSayfa", "Sayfa sayfa")
m("hatimBolmeCuzAciklama", "{pay#} pay; her pay bir cüz.")
m("hatimBolmeSayfaAciklama", "{pay#} pay; her pay {sayfa#} sayfa.")
m("hatimHedefTarih", "Hedef tarih")
m("hatimHedefYok", "Belirlenmedi")
m("hatimHedefKaldir", "Hedef tarihi kaldır")
m("hataBos", "Bu alan boş bırakılamaz.")
m("hataUzun", "En fazla {sinir#} karakter yazabilirsiniz.")
m("hataLink", "Bu alana link yazılamaz.")
m("hatimCuzSec", "Bir cüz seç")
m("hatimCuzSecAciklama", "Boş bir cüze dokunarak sorumluluğu al.")
m("hatimSayfaSec", "Bir sayfa aralığı seç")
m("hatimSayfaSecAciklama", "Boş bir sayfa aralığına dokunarak sorumluluğu al.")
m("durumOkundu", "Okundu")
m("durumAlindi", "Alındı")
m("durumSenin", "Senin")
m("durumBos", "Boş")
m("hatimCuzAdi", "{no#}. cüz")
m("hatimSayfaAdi", "Sayfa {bas#}–{bit#}")
m("seninPayin", "Senin payın")
m("okumayaBasla", "Okumaya başla")
m("okudum", "Okudum")
m("payiBirak", "Bırak")
m("geriAl", "Geri al")
m("hatimAlinmis", "Bu pay az önce alındı.")
m("hatimSil", "Hatmi sil")
m("hatimSilOnay", "Bu hatim ve işaretlediğiniz paylar bu telefondan silinecek.")
m("hatimTamamMetin", "Bütün paylar okundu. Allah kabul etsin.")
m("hatimAltNot", "Hesap gerekmez. Hatim bilgileri yalnızca bu telefonda durur.")

# --- Esmâ-ül Hüsnâ ---------------------------------------------------------
m("esmaBaslik", "Esmâ-ül Hüsnâ")
m("esmaAltBaslik", "Allah'ın en güzel 99 ismi")
m("esmaAraIpucu", "İsim veya anlam ara")
m("gununIsmi", "Günün ismi")
m("isimNo", "{no#}. isim")
m("zikirmatikteZikret", "Zikirmatik'te zikret")

arb = {"@@locale": "tr"}
for anahtar, metin in M.items():
    yer = re.findall(r"\{(\w+)(#?)\}", metin)
    arb[anahtar] = re.sub(r"\{(\w+)#\}", r"{\1}", metin)
    if yer:
        arb["@" + anahtar] = {
            "placeholders": {
                ad: {"type": "int" if tam else "String"} for ad, tam in yer
            }
        }
with open("lib/l10n/app_tr.arb", "w", encoding="utf-8", newline="\n") as f:
    json.dump(arb, f, ensure_ascii=False, indent=2)
    f.write("\n")
print("metin:", len(M))
